cd 'junior_qianghao-fengqing'
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
pause