cd 'junior_qianghao-malinlin'
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
pause