cd junior_qianghao-zhangyangcheng
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
pause