cd junior_qianghao-tanyinhao
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
pause