cd junior_qianghao-zhengmenghan
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
scrapy crawl junior_qh
pause